
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "0"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_2: ${POSTGRES_DB_2}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
