version: '3.8'

services:
  web:
    image: python:3.13.1-slim
    container_name: python_app
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=WoaTR8oS473
      - POSTGRES_DB=financial_data_set
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: financial_data_set
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:    
