services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "0"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./PKDD/static:/app/PKDD/static:ro
    depends_on:
      - web

  db:
    extends:
      file: docker-compose.yaml
      service: db

volumes:
  db_data:
    external: true